spring:
  application:
    name: ComplaintSerivce

  output:
    ansi:
      enabled: always

eureka:
  client:
    service-url:
      defaultZone: https://fireurekaserver.onrender.com/eureka # Eureka server URL
    register-with-eureka: true
    fetch-registry: true
server:
  servlet:
    context-path: /api/complaintService/
