spring:
  application:
    name: AuthService
  output:
    ansi:
      enabled: always


  datasource:
    url: jdbc:postgresql://dpg-d3h55fb3fgac739gi130-a.oregon-postgres.render.com:5432/efir_yylb
    username: shrihari
    password: 7cbgAIkskKPC4flVyHhXfOj7BpPtUUnV
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8082

jwt:
  secret: e4b8c7a1d95b47ef98a1asdfasdfnsndfjnjnnsdfnc25c6b69a3b54b24f5d1de0c9c86a77d8d6b6a2e83f2

eureka:
  client:
    service-url:
      defaultZone: https://fireurekaserver.onrender.com/eureka # Eureka server URL
    register-with-eureka: true
    fetch-registry: true
